service: streaming-titles-api

package:
  individually: true

provider:
  name: aws
  runtime: python3.9
  region: us-east-2
  stage: ${opt:stage, "dev"}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    layer:
      name: streaming-titles-api-layer
      description: Layer for streaming-titles-api
      compatibleRuntimes:
        - python3.9

functions:
  app:
    package:
      patterns:
        - "main.py"
        - "!requirements.txt"
        - "!package.json"
        - "!package-lock.json"
        - "!.serverless/**"
        - "!.virtualenv/**"
        - "!node_modules/**"

    handler: main.handler
    environment:
      STAGE: ${self:provider.stage}
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
            method: get
            path: /
      - http:
          path: /{proxy+}
          method: any
